# coding: utf-8

HTTP = "http"
HTTPS = "https"

HTTP_PORT = 80
HTTPS_PORT = 443

MAX_HEADER_LENGTH = 8192
MAX_HEADERS = 8192

METH_GET = "GET"
METH_POST = "POST"
METH_PUT = "PUT"
METH_DELETE = "DELETE"
METH_HEAD = "HEAD"
METH_OPTIONS = "OPTIONS"
METH_TRACE = "TRACE"
METH_PATCH = "PATCH"

POST_METHOD = {
    METH_PATCH,
    METH_POST,
    METH_PUT,
}
